# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notas.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'notas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotas.proto\"+\n\x0bNotaRequest\x12\r\n\x05nota1\x18\x01 \x01(\x01\x12\r\n\x05nota2\x18\x02 \x01(\x01\"a\n\x0cNotaResponse\x12\r\n\x05media\x18\x01 \x01(\x01\x12\x10\n\x08\x61provado\x18\x02 \x01(\x08\x12\x11\n\treprovado\x18\x03 \x01(\x08\x12\x1d\n\x15nota_final_necessaria\x18\x04 \x01(\x01\x32:\n\x0bNotaService\x12+\n\x0c\x43\x61lcularNota\x12\x0c.NotaRequest\x1a\r.NotaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTAREQUEST']._serialized_start=15
  _globals['_NOTAREQUEST']._serialized_end=58
  _globals['_NOTARESPONSE']._serialized_start=60
  _globals['_NOTARESPONSE']._serialized_end=157
  _globals['_NOTASERVICE']._serialized_start=159
  _globals['_NOTASERVICE']._serialized_end=217
# @@protoc_insertion_point(module_scope)
